/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package composite;

public class App {
    public static void main(String[] args) {
        CompoundGraphic cg = new CompoundGraphic();
        
        Dot dot1 = new Dot(1, 1);
        Circle circle1 = new Circle(5, 5, 2);
        
        cg.add(dot1);
        cg.add(circle1);
        cg.draw();
        
        Dot dot2 = new Dot(0, 0);
        Circle circle2 = new Circle(3, 3, 3);
        
        cg.clear();
        cg.add(dot2);
        cg.remove(dot1);
        cg.add(circle2);
        cg.draw();
        
        Circle circle3 = new Circle(6, 6, 3);
        
        cg.add(circle3);
        cg.draw(); 
    }
}
