/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package builder;

public class App {
    public static void main(String[] args) {
        CarBuilder builder;
        
        builder = new CarBuilderLigth();
        builder
            .setEngine("Engine V3")
            .setGPS("GPS V1")
            .setSeats("Light seats")
            .setTripComputer("Intel")
            .setAutoType("BMV");
        
        Car newCarLigth1 = builder.build();
        
        builder.reset();
        
        builder
            .setEngine("Engine V2")
            .setGPS("GPS V2")
            .setSeats("Default seats")
            .setTripComputer("AMD")
            .setAutoType("Nissan");
        
        Car newCarLigth2 = builder.build();
        
        builder = new CarBuilderTruck();
        builder
            .setEngine("Engine V3")
            .setGPS("GPS V1")
            .setSeats("Light seats")
            .setTripComputer("Intel")
            .setAutoType("BMV");
        
        Car newCarTruck1 = builder.build();
        
        builder.reset();
        
        builder
            .setEngine("Engine V2")
            .setGPS("GPS V2")
            .setSeats("Default seats")
            .setTripComputer("AMD")
            .setAutoType("Nissan");
        
        Car newCarTruck2 = builder.build();
        
        System.out.println(newCarLigth1.toString());
        System.out.println(newCarLigth2.toString());
        System.out.println(newCarTruck1.toString());
        System.out.println(newCarTruck2.toString());
    }
}
