/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package okhttp;

import okhttp3.Request;
import okhttp3.Response;

import java.io.IOException;

import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Interceptor;
import okhttp3.OkHttpClient;

public class App {
	public static void main(String[] args) {
		// Создание клиента и запроса
		OkHttpClient client = new OkHttpClient.Builder().addInterceptor(new Interceptor() {
			@Override
			public Response intercept(Chain arg0) throws IOException {
				Request req = arg0.request();
				Response res = arg0.proceed(req);
				System.out.println("Request: " + req.url().url().toString());
				System.out.println("Response: " + res.isSuccessful());
				return res;
			}
		}).build();

		Request request = new Request.Builder().url("https://www.google.ru/").build();

		// Исполнение запроса синхронно,в потоке вызывающем `execute`
		try {
			Response response = client.newCall(request).execute();

			String serverAnswer = response.body().string();

			System.out.println(serverAnswer);
		} catch (IOException e) {
			e.printStackTrace();
		}

		System.out.println("--------------------------------------");

		// исполняем запрос асинхронно,в потоке вызывающем `execute`
		Call asyncCall = client.newCall(request);

		asyncCall.enqueue(new Callback() {

			@Override
			public void onFailure(Call arg0, IOException arg1) {
				// TODO Auto-generated method stub
				arg1.printStackTrace();
			}

			@Override
			public void onResponse(Call arg0, Response arg1) throws IOException {
				// TODO Auto-generated method stub
				System.out.println(arg1.body().string());
				System.exit(0);
			}
		});
	}
}
