/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adapter;

public class App {
    public static void main(String[] args) {
        USB cardReader = new CardReader(new MemoryCard());
        cardReader.connectWithUsbCable();
    }
}
