/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binarysearch;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int[] nums = new int[] { 2, 23, 56, 31, 17, 48, 23 };
        int key = 23;
        System.out.println("Array: " + Arrays.toString(nums));
        System.out.println("Key: " + key);
        System.out.println("Search result: " + binarySearch(nums, key, 0, nums.length - 1));
    }

    public static int binarySearch(int[] array, int key, int left, int right) {
        int keyIndex = -1;

        if (left == right) {
            if (array[left] == key) {
                keyIndex = left;
                return keyIndex;
            } else {
                return keyIndex;
            }
        }

        int middle = left + (right - left) / 2;

        if (key > array[middle]) {
            keyIndex = binarySearch(array, key, middle + 1, right);
            return keyIndex;
        } else if (array[middle] > key) {
            keyIndex = binarySearch(array, key, left, middle - 1);
            return keyIndex;
        }

        keyIndex = middle;
        return keyIndex;
    }
}
