/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package strategy;

public class App {
    public static void main(String[] args) {
        int a, b;
        a = 4;
        b = 2;
        
        OperationContext context = new OperationContext(new AddOperation());
        System.out.println(context.getResult(a, b));
        
        context.setOperation(new SubstractOperation());
        System.out.println(context.getResult(a, b));
    }
}
