/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junitusage;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello world");
    }

    public static int generateRandFromTwo() {
        return (int) (Math.random() * 10) + 1;
    }

    public void throwingMethod() {
        throw new IndexOutOfBoundsException();
    }

    public boolean randBool() {
        return Math.random() > 0.5;
    }
}
