/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package serialization;

import org.junit.Test;
import static org.junit.Assert.*;

public class SerializationTest {
    @Test public void appHasAClassName() {
        Serialization classUnderTest = new Serialization();
        assertNotNull("class name should have a value", classUnderTest.getClass().getSimpleName());
    }
}
