/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interpreter;

public class App {
    public static void main(String[] args) {
        // 10-5
        NumberExpression expression = new Substract(new BinaryNumber("1010"), new BinaryNumber("101"));
        // 20-5
        expression = new Substract(new BinaryNumber("10100"), expression);
        
        System.out.println(expression.interpret());
    }
}
