/*
  * This Java source file was generated by the Gradle 'init' task.
  */
package selenium;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import org.openqa.selenium.By;
import org.openqa.selenium.ElementNotInteractableException;
import org.openqa.selenium.PageLoadStrategy;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class App {
    public static void main(String[] args) throws UnsupportedEncodingException {
        // Creating driver
        ChromeOptions capabilities = new ChromeOptions();
        capabilities.setPageLoadStrategy(PageLoadStrategy.EAGER);
        WebDriver driver = new ChromeDriver(capabilities);

        // Variables
        String pageTitle = null;
        String searchQuery = "Deus Ex";
        List<String> queryResults = new ArrayList<String>();
        List<String> secondQueryResults = new ArrayList<String>();
        String badLogin = "abc@@";
        String badLoginMessage = null;

        // Getting page title
        driver.get("https://www.google.com/");

        generateLoadDelay();

        pageTitle = driver.getTitle();

        // Getting search results
        driver.get(
                String.format(
                        "https://www.google.com/search?q=%s",
                        URLEncoder.encode(searchQuery, StandardCharsets.UTF_8.toString())));

        generateLoadDelay();

        String findedQueryResult = "";
        for (WebElement findedElement : driver.findElements(By.xpath("//div[@data-snhf]//h3"))) {
            findedQueryResult = findedElement.getText();
            if (!queryResults.contains(findedQueryResult)) {
                queryResults.add(findedQueryResult);
            }
        }

        if (queryResults.get(0).equals("Google")) {
            queryResults.remove(0);
        }

        // Getting search results second way
        driver.get("https://www.google.com/");

        generateLoadDelay();

        WebElement searchTextInput = driver.findElement(By.xpath("//textarea"));
        searchTextInput.sendKeys(searchQuery);
        searchTextInput.submit();

        generateLoadDelay();

        findedQueryResult = "";
        for (WebElement findedElement : driver.findElements(By.xpath("//div[@data-snhf]//h3"))) {
            findedQueryResult = findedElement.getText();
            if (!secondQueryResults.contains(findedQueryResult)) {
                secondQueryResults.add(findedQueryResult);
            }
        }

        if (secondQueryResults.get(0).equals("Google")) {
            secondQueryResults.remove(0);
        }

        // Getting bad login message
        driver.get("https://www.google.com/");

        generateLoadDelay();

        WebElement loginButtonText = driver.findElement(By.xpath("//span[@class=\"gb_Id\"]"));
        WebElement loginButton = loginButtonText.findElement(By.xpath("./.."));
        loginButton.click();

        generateLoadDelay();

        WebElement loginTextInput = driver.findElement(By.xpath("//input[@type=\"email\"]"));
        loginTextInput.sendKeys(badLogin);
        List<WebElement> loginAcceptButtonParts =
                driver.findElements(By.xpath("//button[@data-idom-class and @jsname]/.."));
        for (WebElement part : loginAcceptButtonParts) {
            try {
                part.click();
            } catch (ElementNotInteractableException e) {
                System.out.println("Element not normally interactable");
            }
        }

        generateLoadDelay();

        WebElement errorMessage = driver.findElement(By.xpath("//div[@aria-atomic]"));
        errorMessage = errorMessage.findElement(By.xpath("./.."));
        generateLoadDelay();
        badLoginMessage = errorMessage.getText();

        // Output
        System.out.println("---------------Page title---------------");
        System.out.println(pageTitle);

        System.out.println("---------------Query results first way---------------");
        for (String queryResult : queryResults) {
            System.out.println(queryResult);
        }

        System.out.println("---------------Query results second way---------------");
        for (String queryResult : secondQueryResults) {
            System.out.println(queryResult);
        }

        System.out.println("---------------Bad login message---------------");
        System.out.println(badLoginMessage);

        // Closing driver
        driver.quit();
    }

    public static void generateLoadDelay() {
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
