/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package factory;

public class App {
    static Dialog dialog;
    
    public static void main(String[] args) throws Exception {
        initialize();
        dialog.render();
    }
    
    public static void initialize() throws Exception {
        String os = "Win";
        if (os.equals("Win")) {
            dialog = new WindowsDialog();
        } else if (os.equals("Web")) {
            dialog = new WebDialog();
        } else {
            throw new Exception("Unknown OS");
        }
    }
}
