/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package visitor;

import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        List <Shape> shapes = new ArrayList<Shape>();
        
        Shape dot = new Dot(0, 0);
        dot.move(10, -3);
        
        Shape circle = new Circle(0, 0, 4);
        circle.move(5, -6);
        
        shapes.add(dot);
        shapes.add(circle);
        
        Visitor visitor = new StepVisitor();
        
        for(Shape shape:shapes) {
            System.out.println("===Before visitor===");
            shape.draw();
            System.out.println("===After visitor===");
            shape.accept(visitor);
        }
    }
}
