/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package decorator;

public class App {
    public static void main(String[] args) {
        String value = "12";

        NumberInString numberInString;

        numberInString = new IntNumberInString();
        numberInString.setValue(value);

        String oldValue = value;

        numberInString = new NumberInStringUsingIncrementDecorator(numberInString);
        System.out.println(oldValue + " to " + numberInString.getValue());

        oldValue = numberInString.getValue();

        numberInString = new NumberInStringUsingIncrementDecorator(numberInString);
        System.out.println(oldValue + " to " + numberInString.getValue());

        oldValue = "11";

        numberInString = new LongNumberInString();

        numberInString = new NumberInStringUsingBinaryInputDecorator(numberInString);

        numberInString.setValue(oldValue);

        value = numberInString.getValue();

        System.out.println(oldValue + " to " + value);
    }
}
