/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package retrofit;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.lang.reflect.Method;
import java.util.Arrays;

class AppTest {
    @Test void appHasAMain() {
        App classUnderTest = new App();
        Method[] methods = classUnderTest.getClass().getMethods();
        assertTrue(
                Arrays
                .stream(methods)
                .map(m -> m.getName())
                .toList()
                .contains("main")
                , "app should have a main"
                );
    }
}
