/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package abstractfactory;

public class App {
    static GUIFactory factory;
    static Button button;
    static Checkbox checkbox;
    
    public static void main(String[] args) throws Exception {
        initialize();
        button = factory.createButton();
        button.paint();
        checkbox = factory.createCheckbos();
        checkbox.paint();
    }
    
    public static void initialize() throws Exception {
        String os = "Mac";
        if (os.equals("Win")) {
            factory = new WinFactory();
        } else if (os.equals("Mac")) {
            factory = new MacFactory();
        } else {
            throw new Exception("Unknown OS");
        }
    }
}
