/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package caveatemptor;

import java.io.IOException;
import java.util.Scanner;

import javax.persistence.EntityManagerFactory;

import caveatemptor.cli.ApplicationCLI;
import caveatemptor.configuration.ApplicationConfigReader;
import caveatemptor.configuration.HiberConfiguration;
import caveatemptor.controllers.BidController;
import caveatemptor.controllers.BillingDetailsController;
import caveatemptor.controllers.ItemController;
import caveatemptor.controllers.UserController;
import caveatemptor.models.Bid;
import caveatemptor.models.BillingDetails;
import caveatemptor.models.Item;
import caveatemptor.models.User;

public class App {
    public static void main(String[] args) throws IOException {
        configureApplication();

        runApplication();
    }

    private static void configureApplication() throws IOException {
        ApplicationConfigReader configReader = new ApplicationConfigReader();

        HiberConfiguration.addEntity(User.class);
        HiberConfiguration.addEntity(Bid.class);
        HiberConfiguration.addEntity(Item.class);
        HiberConfiguration.addEntity(BillingDetails.class);
        HiberConfiguration.build(configReader);
    }

    private static void runApplication() {
        EntityManagerFactory managerFactory = HiberConfiguration.getEntityManagerFactory();

        Scanner scanner = new Scanner(System.in);

        BidController bidController = new BidController(managerFactory, scanner);
        BillingDetailsController billingDetailsController = new BillingDetailsController(managerFactory, scanner);
        ItemController itemController = new ItemController(managerFactory, scanner);
        UserController userController = new UserController(managerFactory, scanner);

        ApplicationCLI appCLI = new ApplicationCLI(scanner, bidController, billingDetailsController, itemController,
                userController);

        appCLI.run();

        managerFactory.close();
    }
}
