/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flyweight;

public class App {
    public static void main(String[] args) {

        System.out.println("Simple car");

        Car simpleCar = new Car();
        simpleCar.setCarType("Standard");
        simpleCar.setEngineType("V6");
        simpleCar.setMaxSpeed(220);
        simpleCar.setModelName("Nissan");

        Car simpleCar2 = new Car();
        simpleCar2.setCarType("Truck");
        simpleCar2.setEngineType("V8");
        simpleCar2.setMaxSpeed(250);
        simpleCar2.setModelName("BMW");

        Car simpleCar3 = new Car();
        simpleCar3.setCarType("Truck");
        simpleCar3.setEngineType("V8");
        simpleCar3.setMaxSpeed(250);
        simpleCar3.setModelName("Opel");

        Car simpleCar4 = new Car();
        simpleCar4.setCarType("Standard");
        simpleCar4.setEngineType("V6");
        simpleCar4.setMaxSpeed(220);
        simpleCar4.setModelName("Tayota");

        System.out.println("Optimized car");

        CarEngine lightEngine = new CarEngine();
        lightEngine.setEngineType("V6");
        lightEngine.setMaxSpeed(220);

        CarEngine truckEngine = new CarEngine();
        truckEngine.setEngineType("V8");
        truckEngine.setMaxSpeed(250);

        CarOptimized car = new CarOptimized();
        car.setCarType("Standard");
        car.setEngine(lightEngine);
        car.setModelName("Nissan");

        CarOptimized car2 = new CarOptimized();
        car2.setCarType("Truck");
        car2.setEngine(truckEngine);
        car2.setModelName("BMW");

        CarOptimized car3 = new CarOptimized();
        car3.setCarType("Truck");
        car3.setEngine(truckEngine);
        car3.setModelName("Opel");

        CarOptimized car4 = new CarOptimized();
        car4.setCarType("Standard");
        car4.setEngine(lightEngine);
        car4.setModelName("Tayota");
    }
}
