/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package templatemethod;

public class App {
    public static void main(String[] args) {
        EssayTemplate essay = new ShortEssay("Programming - An Art");
        essay.writeEssay();
        
        System.out.println("===========");
        
        essay = new LongEssay("Programming - An Art");
        essay.writeEssay();
    }
}
