/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linearsearch;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int[] nums = new int[] {2, 23, 56, 31, 17, 48, 23};
        int key = 23;
        System.out.println("Array: " + Arrays.toString(nums));
        System.out.println("Key: " + key);
        System.out.println("Search result: " + linearSearch(nums, key));
    }
    
    public static int linearSearch(int[] array, int key) {
        int keyIndex = -1;
        
        for(int index = 0; index < array.length; index++) {
            if(array[index] == key) {
                keyIndex = index;
                break;
            }
        }
        
        return keyIndex;
    }
}
