/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package retrofit;

import retrofit2.Call;
import retrofit2.Response;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import okhttp3.OkHttpClient;
import okhttp3.ResponseBody;
import retrofit.requests.GoogleRequests;
import retrofit2.Retrofit;

public class App {

    public static void main(String[] args) {
        String basePageHtml = "";   
        String queryPageHtml = "";    
        
        // Создание клиента
        OkHttpClient httpClient = new OkHttpClient.Builder().build();
        Retrofit retrofitClient = new Retrofit
                                      .Builder()
                                      .client(httpClient)
                                      .baseUrl("https://google.com")
                                      .build();
        
        // Создание группы запросов
        GoogleRequests requests = retrofitClient.create(GoogleRequests.class);
        
        System.out.println("Base page");
        System.out.println("===================================================================");
        
        // Выполнение запроса и получение ответа
        Call<ResponseBody> basePageRequestCall = requests.getBasePage();
        Response<ResponseBody> baseResponseBody = null;
        try {
            baseResponseBody = basePageRequestCall.execute();
            
            if(baseResponseBody != null) {
                basePageHtml = baseResponseBody.body().string();
            }
            
            // Создание и открытие временного html файла с содержимым
            Path temp = Files.createTempFile("basePageHtml", ".html");
            
            FileWriter fWriter = new FileWriter(temp.toFile());
            fWriter.write(basePageHtml);
            fWriter.flush();
            
            Runtime.getRuntime().exec("explorer "+temp.toFile());
            
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        System.out.println("");
        System.out.println("Query page");
        System.out.println("===================================================================");
        
        // Выполнение запроса и получение ответа
        Call<ResponseBody> queryPageRequestCall = requests.search("news");
        Response<ResponseBody> queryResponseBody = null;
        try {
            queryResponseBody = queryPageRequestCall.execute();
            
            if(queryResponseBody != null) {
                queryPageHtml = queryResponseBody.body().string();
            }
            
            // Создание и открытие временного html файла с содержимым
            Path temp = Files.createTempFile("basePageHtml", ".html");
            
            FileWriter fWriter = new FileWriter(temp.toFile());
            fWriter.write(queryPageHtml);
            fWriter.flush();
            
            Runtime.getRuntime().exec("explorer "+temp.toFile());
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        System.exit(0);
    }
}
