/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package command;

import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        List<Integer> nums = new ArrayList<Integer>();
        
        CollectionEditor<Integer> editor = new CollectionEditor<Integer>(nums);
        
        AddCommand<Integer> addCommand = new AddCommand<Integer>(editor, 1);
        AddCommand<Integer> addCommand2 = new AddCommand<Integer>(editor, 2);
        RemoveCommand<Integer> removeCommand = new RemoveCommand<Integer>(editor, 1);
        
        CollectionUtils utils = new CollectionUtils();
        utils.addCommand(addCommand);
        utils.addCommand(addCommand2);
        utils.addCommand(removeCommand);
        
        utils.execCommandsQueue();
        
        System.out.println(nums.toString());
    }
}
