/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iterator;

public class App {
    public static void main(String[] args) {
        SimpleList<Integer> numsList = new SimpleList<Integer>();
        numsList.addNode(1);
        numsList.addNode(2);
        numsList.addNode(3);
        numsList.addNode(4);
        
        for(SimpleList<Integer> element : numsList) {
            System.out.println(element.getValue());
        }
        
        SimpleList<String> stringList = new SimpleList<String>();
        stringList.addNode("One");
        stringList.addNode("Two");
        stringList.addNode("Three");
        stringList.addNode("Four");
        
        for(SimpleList<String> element : stringList) {
            System.out.println(element.getValue());
        }
        
        SimpleListIterator<Integer> iterator = 
                new SimpleListIterator<Integer>(numsList);
        
        System.out.println(iterator.hasNext());
        System.out.println(iterator.next().getValue());
    }
}
