/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bridge;

public class App {
    public static void main(String[] args) {
       Device myTV = new TV();
       
       Remote myRemote = new Remote(myTV);
       int oldChannel = myTV.getChannel();
       myRemote.channelUp();
       int newChannel = myTV.getChannel();
       System.out.println("TV channel changed from " + oldChannel + " to " + newChannel);
       
       AdvancedRemote myAdvancedRemote = new AdvancedRemote(myTV);
       myAdvancedRemote.volumeUp();
       int oldVolume = myTV.getVolume();
       myAdvancedRemote.mute();
       int newVolume = myTV.getVolume();
       System.out.println("TV volume changed from " + oldVolume + " to " + newVolume);
       
       OldRemote myOldRemote = new OldRemote(myTV);
       oldChannel = myTV.getChannel();
       myOldRemote.channelUp();
       newChannel = myTV.getChannel();
       System.out.println("TV channel changed from " + oldChannel + " to " + newChannel + " with delay");
       
       Device myRadio = new Radio();
       
       myRemote = new Remote(myRadio);
       oldChannel = myRadio.getChannel();
       myRemote.channelUp();
       newChannel = myRadio.getChannel();
       System.out.println("Radio channel changed from " + oldChannel + " to " + newChannel);
    }
}
