/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworldh;

import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;

public class App {
    public static void main(String[] args) {
        Message msg = new Message();
        msg.setText("Hello world from hibernate!");

        System.out.println(msg.getText());

        HiberConfiguration.addEntity(Message.class);
        HiberConfiguration.build();

        EntityManager em = HiberConfiguration.getEntityManager();

        EntityTransaction tx = em.getTransaction();
        tx.begin();

        em.persist(msg);

        tx.commit();

        em.close();
    }
}
